// apps/desktop/src/renderer/components/gcode-wordmark.tsx
/**
 * Inline SVG wordmark for "GCode" — renders at currentColor, no font dependency.
 *
 * Uses a monospaced system stack so the product name is always readable as GCode
 * (never legacy product glyph outlines).
 */
export function GCodeWordmark({ className }: { className?: string }) {
	return (
		<svg
			viewBox="0 0 120 28"
			fill="none"
			xmlns="http://www.w3.org/2000/svg"
			className={className}
			style={{ overflow: "visible" }}
			aria-hidden="true"
			role="img"
		>
			<title>GCode</title>
			<text
				x="0"
				y="22"
				fill="currentColor"
				fontFamily="ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace"
				fontSize="22"
				fontWeight="800"
				letterSpacing="1.2"
			>
				GCode
			</text>
		</svg>
	)
}

// apps/desktop/src/renderer/lit/components/gcode-wordmark.ts
/**
 * Product wordmark — progressive Lit migration of GCodeWordmark.
 * Inherits color and size from the Lit host token surface.
 */
import { html, LitElement } from "lit"
import { customElement } from "lit/decorators.js"
import {
	WORDMARK_FONT_FAMILY,
	WORDMARK_LABEL,
	WORDMARK_VIEWBOX,
} from "../wordmark"
import { styles } from "./gcode-wordmark.css.js"

@customElement("gcode-wordmark")
export class GcodeWordmarkElement extends LitElement {
	static styles = styles

	render() {
		return html`
			<svg
				viewBox=${WORDMARK_VIEWBOX}
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
				aria-hidden="true"
				role="img"
			>
				<title>${WORDMARK_LABEL}</title>
				<text x="0" y="22" font-family=${WORDMARK_FONT_FAMILY}>
					${WORDMARK_LABEL}
				</text>
			</svg>
		`
	}
}

declare global {
	interface HTMLElementTagNameMap {
		"gcode-wordmark": GcodeWordmarkElement
	}
}
